[package]
name = "rust_blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
k256 = { version = "0.13", features = ["ecdsa"] }
rand_core = "0.6"
hex = "0.4.3"
