[package]
name = "rust_blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10.8"
k256 = { version = "0.13", features = ["ecdsa"] }
rand_core = "0.6"
hex = "0.4.3"
num-bigint = "0.4.6"
bincode = "2.0.1"
